/**
 * File generated by Magnet rest2mobile 1.0 - Oct 17, 2014 1:41:16 AM
 * @see {@link http://developer.magnet.com}
 */

package com.magnetapi.examples.controller.api.test;

import android.test.InstrumentationTestCase;
import android.test.suitebuilder.annotation.SmallTest;
import android.test.suitebuilder.annotation.Suppress;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.exception.SchemaException;
import java.util.concurrent.ExecutionException;

import com.magnetapi.examples.controller.api.Earthquakes;
import com.magnetapi.examples.controller.api.EarthquakesFactory;
import com.magnetapi.examples.model.beans.*;

/**
* This is generated stub to test {@link Earthquakes}
* <p>
* All test cases are suppressed by defaullt. To run the test, you need to fix all the FIXMEs first :
* <ul>
* <li>Set proper value for the parameters
* <li>Remove out the @Suppress annotation
* <li>(optional)Add more asserts for the result
* <ul><p>
*/

public class EarthquakesTest extends InstrumentationTestCase {
  private Earthquakes earthquakes;

  @Override
  protected void setUp() throws Exception {
    super.setUp();

    // Instantiate a controller
    MagnetMobileClient magnetClient = MagnetMobileClient.getInstance(this.getInstrumentation().getTargetContext());
    EarthquakesFactory controllerFactory = new EarthquakesFactory(magnetClient);
    earthquakes = controllerFactory.obtainInstance();

    assertNotNull(earthquakes);
  }

  /**
    * Generated unit test for {@link Earthquakes#getEarthquakes}
    */
  @Suppress //FIXME : set proper parameter value and un-suppress this test case
  @SmallTest
  public void testGetEarthquakes() throws SchemaException, ExecutionException, InterruptedException {
    // FIXME : set proper value for the parameters
    String yyy = null;
    String mm = null;
    String min_magnitude = null;
    String limit = null;

    Call<EarthquakesResult> callObject = earthquakes.getEarthquakes(
      yyy, 
      mm, 
      min_magnitude, 
      limit, null);
    assertNotNull(callObject);

    EarthquakesResult result = callObject.get();
    assertNotNull(result);
    //TODO : add more asserts
  }

}
