/**
 * File generated by Magnet rest2mobile 1.0 - Oct 17, 2014 1:41:16 AM
 * @see {@link http://developer.magnet.com}
 */

package com.magnetapi.examples.model.beans;

import java.util.List;

/**
 * Generated from json example
{
  "count" : "2",
  "earthquakes" : [ {
    "src" : "us",
    "eqid" : "c0002fj4",
    "timedate" : "2011-03-3107:15:30",
    "lat" : "38.9536",
    "lon" : "142.0174",
    "magnitude" : "6.2",
    "depth" : "39.6",
    "region" : "neartheeastcoastofHonshu,Japan"
  }, {
    "src" : "us",
    "eqid" : "b0001q2y",
    "timedate" : "2011-03-0612:31:56",
    "lat" : "-18.1084",
    "lon" : "-69.3758",
    "magnitude" : "6.2",
    "depth" : "87.8",
    "region" : "Putre,Chile"
   ...

 */

public class EarthquakesResult {

  
  private String count;

  
  private List<Earthquake> earthquakes;

  public String getCount() {
    return count;
  }
  public List<Earthquake> getEarthquakes() {
    return earthquakes;
  }

  /**
  * Builder for EarthquakesResult
  **/
  public static class EarthquakesResultBuilder {
    private EarthquakesResult toBuild = new EarthquakesResult();

    public EarthquakesResultBuilder() {
    }

    public EarthquakesResult build() {
      return toBuild;
    }

    public EarthquakesResultBuilder count(String value) {
      toBuild.count = value;
      return this;
    }
    public EarthquakesResultBuilder earthquakes(List<Earthquake> value) {
      toBuild.earthquakes = value;
      return this;
    }
  }
}
