/**
 * File generated by Magnet rest2mobile 1.0 - Oct 23, 2014 2:40:59 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magnetapi.examples.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import com.magnetapi.examples.model.beans.*;

public interface AsanaUsers {

  /**
   * Generated from URL GET https://app.asana.com/api/1.0/users
   * GET api/1.0/users
   * @param Authorization  style:HEADER
   * @param listener
   * @return AsanaUsersResult
   */
  Call<AsanaUsersResult> getAsanaUsers(
     String Authorization,
     StateChangedListener listener
  );


}
