/**
 * File generated by Magnet rest2mobile 1.0 - Oct 22, 2014 11:45:03 AM
 * @see {@link http://developer.magnet.com}
 */

package com.magnetapi.examples.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;
import com.magnet.android.mms.controller.RequestSchema.JMeta;
import com.magnet.android.mms.controller.RequestSchema.JParam;

import java.util.Arrays;
import java.util.Collection;

import com.magnetapi.examples.model.beans.*;

public class GoogleTimeZoneFactory extends ControllerFactory<GoogleTimeZone> {
  public GoogleTimeZoneFactory(MagnetMobileClient magnetClient) {
    super(GoogleTimeZone.class, GoogleTimeZoneSchemaFactory.getInstance().getSchema(), magnetClient);
  }

  // Schema factory for controller GoogleTimeZone
  public static class GoogleTimeZoneSchemaFactory extends AbstractControllerSchemaFactory {
    private static GoogleTimeZoneSchemaFactory __instance;

    public static synchronized GoogleTimeZoneSchemaFactory getInstance() {
      if(null == __instance) {
        __instance = new GoogleTimeZoneSchemaFactory();
      }

      return __instance;
    }

    private GoogleTimeZoneSchemaFactory() {}

    protected synchronized void initSchemaMaps() {
      if(null != schema) {
        return;
      }

      schema = new RequestSchema();
      schema.setRootPath("");

      //controller schema for controller method getTimeZone
      JMethod method1 = addMethod("getTimeZone",
        "maps/api/timezone/json",
        "GET",
        TimeZoneResult.class,
        null,
        null,
        Arrays.asList("application/json"));
      method1.setBaseUrl("https://maps.googleapis.com");
      method1.addParam("location",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("timestamp",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("sensor",
        "QUERY",
        String.class,
        null,
        "",
        true);
    }

  }

}
