/**
 * File generated by Magnet rest2mobile 1.0 - Oct 22, 2014 11:45:03 AM
 * @see {@link http://developer.magnet.com}
 */

package com.magnetapi.examples.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import com.magnetapi.examples.model.beans.*;

public interface GoogleTimeZone {

  /**
   * Generated from URL GET https://maps.googleapis.com/maps/api/timezone/json?location=39.6034810,-119.6822510&timestamp=1331161200&sensor=true
   * GET maps/api/timezone/json
   * @param location  style:QUERY
   * @param timestamp  style:QUERY
   * @param sensor  style:QUERY
   * @param listener
   * @return TimeZoneResult
   */
  Call<TimeZoneResult> getTimeZone(
     String location,
     String timestamp,
     String sensor,
     StateChangedListener listener
  );


}
