/**
 * File generated by Magnet rest2mobile 1.0 - Oct 17, 2014 1:41:16 AM
 * @see {@link http://developer.magnet.com}
 */

package com.magnetapi.examples.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;
import com.magnet.android.mms.controller.RequestSchema.JMeta;
import com.magnet.android.mms.controller.RequestSchema.JParam;

import java.util.Arrays;
import java.util.Collection;

import com.magnetapi.examples.model.beans.*;

public class EarthquakesFactory extends ControllerFactory<Earthquakes> {
  public EarthquakesFactory(MagnetMobileClient magnetClient) {
    super(Earthquakes.class, EarthquakesSchemaFactory.getInstance().getSchema(), magnetClient);
  }

  // Schema factory for controller Earthquakes
  public static class EarthquakesSchemaFactory extends AbstractControllerSchemaFactory {
    private static EarthquakesSchemaFactory __instance;

    public static synchronized EarthquakesSchemaFactory getInstance() {
      if(null == __instance) {
        __instance = new EarthquakesSchemaFactory();
      }

      return __instance;
    }

    private EarthquakesSchemaFactory() {}

    protected synchronized void initSchemaMaps() {
      if(null != schema) {
        return;
      }

      schema = new RequestSchema();
      schema.setRootPath("");

      //controller schema for controller method getEarthquakes
      JMethod method1 = addMethod("getEarthquakes",
        "api/eqs/{yyy}/{mm}",
        "GET",
        EarthquakesResult.class,
        null,
        null,
        Arrays.asList("application/json"));
      method1.setBaseUrl("http://www.seismi.org");
      method1.addParam("yyy",
        "TEMPLATE",
        String.class,
        null,
        "",
        false);
      method1.addParam("mm",
        "TEMPLATE",
        String.class,
        null,
        "",
        false);
      method1.addParam("min_magnitude",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("limit",
        "QUERY",
        String.class,
        null,
        "",
        true);
    }

  }

}
