/**
 * File generated by Magnet rest2mobile 1.0 - Oct 22, 2014 11:45:03 AM
 * @see {@link http://developer.magnet.com}
 */

package com.magnetapi.examples.controller.api.test;

import android.test.InstrumentationTestCase;
import android.test.suitebuilder.annotation.SmallTest;
import android.test.suitebuilder.annotation.Suppress;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.exception.SchemaException;
import java.util.concurrent.ExecutionException;

import com.magnetapi.examples.controller.api.GoogleTimeZone;
import com.magnetapi.examples.controller.api.GoogleTimeZoneFactory;
import com.magnetapi.examples.model.beans.*;

/**
* This is generated stub to test {@link GoogleTimeZone}
* <p>
* All test cases are suppressed by defaullt. To run the test, you need to fix all the FIXMEs first :
* <ul>
* <li>Set proper value for the parameters
* <li>Remove out the @Suppress annotation
* <li>(optional)Add more asserts for the result
* <ul><p>
*/

public class GoogleTimeZoneTest extends InstrumentationTestCase {
  private GoogleTimeZone googleTimeZone;

  @Override
  protected void setUp() throws Exception {
    super.setUp();

    // Instantiate a controller
    MagnetMobileClient magnetClient = MagnetMobileClient.getInstance(this.getInstrumentation().getTargetContext());
    GoogleTimeZoneFactory controllerFactory = new GoogleTimeZoneFactory(magnetClient);
    googleTimeZone = controllerFactory.obtainInstance();

    assertNotNull(googleTimeZone);
  }

  /**
    * Generated unit test for {@link GoogleTimeZone#getTimeZone}
    */
  @Suppress //FIXME : set proper parameter value and un-suppress this test case
  @SmallTest
  public void testGetTimeZone() throws SchemaException, ExecutionException, InterruptedException {
    // FIXME : set proper value for the parameters
    String location = null;
    String timestamp = null;
    String sensor = null;

    Call<TimeZoneResult> callObject = googleTimeZone.getTimeZone(
      location, 
      timestamp, 
      sensor, null);
    assertNotNull(callObject);

    TimeZoneResult result = callObject.get();
    assertNotNull(result);
    //TODO : add more asserts
  }

}
