/**
 * File generated by Magnet rest2mobile 1.0 - Oct 23, 2014 2:40:59 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magnetapi.examples.model.beans;


/**
 * Generated from json example
{
  "id" : 107979555105,
  "name" : "JohnDoe"
}

 */

public class Datum {

  
  private Long id;

  
  private String name;

  public Long getId() {
    return id;
  }
  public String getName() {
    return name;
  }

  /**
  * Builder for Datum
  **/
  public static class DatumBuilder {
    private Datum toBuild = new Datum();

    public DatumBuilder() {
    }

    public Datum build() {
      return toBuild;
    }

    public DatumBuilder id(Long value) {
      toBuild.id = value;
      return this;
    }
    public DatumBuilder name(String value) {
      toBuild.name = value;
      return this;
    }
  }
}
