/**
 * File generated by Magnet rest2mobile 1.0 - Oct 20, 2014 3:26:02 PM
 * @see {@link http://developer.magnet.com}
 */

package iampoineer.googledistance.controller.api.test;

import android.test.InstrumentationTestCase;
import android.test.suitebuilder.annotation.SmallTest;
import android.test.suitebuilder.annotation.Suppress;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.exception.SchemaException;
import java.util.concurrent.ExecutionException;

import iampoineer.googledistance.controller.api.GoogleDistance;
import iampoineer.googledistance.controller.api.GoogleDistanceFactory;
import iampoineer.googledistance.model.beans.*;

/**
* This is generated stub to test {@link GoogleDistance}
* <p>
* All test cases are suppressed by defaullt. To run the test, you need to fix all the FIXMEs first :
* <ul>
* <li>Set proper value for the parameters
* <li>Remove out the @Suppress annotation
* <li>(optional)Add more asserts for the result
* <ul><p>
*/

public class GoogleDistanceTest extends InstrumentationTestCase {
  private GoogleDistance googleDistance;

  @Override
  protected void setUp() throws Exception {
    super.setUp();

    // Instantiate a controller
    MagnetMobileClient magnetClient = MagnetMobileClient.getInstance(this.getInstrumentation().getTargetContext());
    GoogleDistanceFactory controllerFactory = new GoogleDistanceFactory(magnetClient);
    googleDistance = controllerFactory.obtainInstance();

    assertNotNull(googleDistance);
  }

  /**
    * Generated unit test for {@link GoogleDistance#getDistance}
    */
  @Suppress //FIXME : set proper parameter value and un-suppress this test case
  @SmallTest
  public void testGetDistance() throws SchemaException, ExecutionException, InterruptedException {
    // FIXME : set proper value for the parameters
    String origins = null;
    String destinations = null;
    String sensor = null;
    String mode = null;
    String language = null;
    String units = null;

    Call<DistanceResult> callObject = googleDistance.getDistance(
      origins, 
      destinations, 
      sensor, 
      mode, 
      language, 
      units, null);
    assertNotNull(callObject);

    DistanceResult result = callObject.get();
    assertNotNull(result);
    //TODO : add more asserts
  }

}
