/**
 * File generated by Magnet rest2mobile 1.0 - Oct 17, 2014 1:41:16 AM
 * @see {@link http://developer.magnet.com}
 */

package com.magnetapi.examples.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import com.magnetapi.examples.model.beans.*;

public interface Earthquakes {

  /**
   * Generated from URL GET http://www.seismi.org/api/eqs/{yyy}/{mm}?min_magnitude=6&limit=500
   * GET api/eqs/{yyy}/{mm}
   * @param yyy  style:TEMPLATE
   * @param mm  style:TEMPLATE
   * @param min_magnitude  style:QUERY
   * @param limit  style:QUERY
   * @param listener
   * @return EarthquakesResult
   */
  Call<EarthquakesResult> getEarthquakes(
     String yyy,
     String mm,
     String min_magnitude,
     String limit,
     StateChangedListener listener
  );


}
