/**
 * File generated by Magnet rest2mobile 1.0 - Oct 20, 2014 3:26:02 PM
 * @see {@link http://developer.magnet.com}
 */

package iampoineer.googledistance.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import iampoineer.googledistance.model.beans.*;

public interface GoogleDistance {

  /**
   * Generated from URL GET http://maps.googleapis.com/maps/api/distancematrix/json?origins=435+Tasso+Street+Palo+Alto+CA&destinations=Embarcadero+Street+San+Francisco+CA&sensor=false&mode=driving&language=en&units=imperial%20
   * GET maps/api/distancematrix/json
   * @param origins  style:QUERY
   * @param destinations  style:QUERY
   * @param sensor  style:QUERY
   * @param mode  style:QUERY
   * @param language  style:QUERY
   * @param units  style:QUERY
   * @param listener
   * @return DistanceResult
   */
  Call<DistanceResult> getDistance(
     String origins,
     String destinations,
     String sensor,
     String mode,
     String language,
     String units,
     StateChangedListener listener
  );


}
