/**
 * File generated by Magnet rest2mobile 1.0 - Oct 23, 2014 1:11:25 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magnetapi.examples.model.beans;


/**
 * Generated from json example
{
  "message" : "InvalidMashapeKey"
}

 */

public class SportsNewsResult {

  
  private String message;

  public String getMessage() {
    return message;
  }

  /**
  * Builder for SportsNewsResult
  **/
  public static class SportsNewsResultBuilder {
    private SportsNewsResult toBuild = new SportsNewsResult();

    public SportsNewsResultBuilder() {
    }

    public SportsNewsResult build() {
      return toBuild;
    }

    public SportsNewsResultBuilder message(String value) {
      toBuild.message = value;
      return this;
    }
  }
}
