/**
 * File generated by Magnet rest2mobile 1.0 - Oct 22, 2014 11:45:03 AM
 * @see {@link http://developer.magnet.com}
 */

package com.magnetapi.examples.model.beans;


import java.util.List;

/**
 * Generated from json example
{
  "dstOffset" : 0,
  "rawOffset" : -28800,
  "status" : "OK",
  "timeZoneId" : "America/Los_Angeles",
  "timeZoneName" : "PacificStandardTime"
}

 */

public class TimeZoneResult {




  
  private Integer dstOffset;

  
  private Integer rawOffset;

  
  private String status;

  
  private String timeZoneId;

  
  private String timeZoneName;

  public Integer getDstOffset() {
    return dstOffset;
  }
  public Integer getRawOffset() {
    return rawOffset;
  }
  public String getStatus() {
    return status;
  }
  public String getTimeZoneId() {
    return timeZoneId;
  }
  public String getTimeZoneName() {
    return timeZoneName;
  }



    /**
  * Builder for TimeZoneResult
  **/
  public static class TimeZoneResultBuilder {
    private TimeZoneResult toBuild = new TimeZoneResult();

    public TimeZoneResultBuilder() {
    }

    public TimeZoneResult build() {
      return toBuild;
    }

    public TimeZoneResultBuilder dstOffset(Integer value) {
      toBuild.dstOffset = value;
      return this;
    }
    public TimeZoneResultBuilder rawOffset(Integer value) {
      toBuild.rawOffset = value;
      return this;
    }
    public TimeZoneResultBuilder status(String value) {
      toBuild.status = value;
      return this;
    }
    public TimeZoneResultBuilder timeZoneId(String value) {
      toBuild.timeZoneId = value;
      return this;
    }
    public TimeZoneResultBuilder timeZoneName(String value) {
      toBuild.timeZoneName = value;
      return this;
    }
  }
}
