/**
 * File generated by Magnet rest2mobile 1.0 - Oct 16, 2014 1:36:55 PM
 * @see {@link http://developer.magnet.com}
 */

package iampoineer.magnetearthquake.model.beans;

import java.util.List;

/**
 * Generated from json example
{
  "count" : "62",
  "earthquakes" : [ {
    "src" : "us",
    "eqid" : "c0002fj4",
    "timedate" : "2011-03-3107:15:30",
    "lat" : "38.9536",
    "lon" : "142.0174",
    "magnitude" : "6.2",
    "depth" : "39.6",
    "region" : "neartheeastcoastofHonshu,Japan"
  }, {
    "src" : "us",
    "eqid" : "c0002fen",
    "timedate" : "2011-03-3100:11:59",
    "lat" : "-16.5663",
    "lon" : "-177.4925",
    "magnitude" : "6.4",
    "depth" : "23.7",
    "region" : "FijiRegion"
   ...

 */

public class CheckQuakeResult {
  
  private String count;
  
  private List<Earthquake> earthquakes;

  public String getCount() {
    return count;
  }
  public List<Earthquake> getEarthquakes() {
    return earthquakes;
  }

  /**
  * Builder for CheckQuakeResult
  **/
  public static class CheckQuakeResultBuilder {
    private CheckQuakeResult toBuild = new CheckQuakeResult();

    public CheckQuakeResultBuilder() {
    }

    public CheckQuakeResult build() {
      return toBuild;
    }

    public CheckQuakeResultBuilder count(String value) {
      toBuild.count = value;
      return this;
    }
    public CheckQuakeResultBuilder earthquakes(List<Earthquake> value) {
      toBuild.earthquakes = value;
      return this;
    }
  }
}
